// src/App.vue
<template>
  <div id="app">
    <UserTable :users="users"/>
  </div>
</template>

<script>
import firebase from 'firebase'
import UserTable from './components/UserTable'

export default {
  name: 'App',
  components: {
    UserTable
  },
  data() {
    return {
      users: []
    }
  },
  mounted() {
    const config = {
      apiKey: 'AIzaSyCN44MXJmFQW42p8VIn7UXn7PxCf2rnVFM',
      authDomain: 'stack-overgol-bot.firebaseapp.com',
      databaseURL: 'https://stack-overgol-bot.firebaseio.com',
      projectId: 'stack-overgol-bot',
      storageBucket: 'stack-overgol-bot.appspot.com',
      messagingSenderId: '564241331900'
    }

    if (!firebase.apps.length) {
      firebase.initializeApp(config)
    }

    const db = firebase.database()

    db.ref().child('/users').once('value').then((s) => {
      const users = Object.values(s.val()).sort((a, b) => {
        if (a.first_name < b.first_name) {
          return -1
        }

        if (a.first_name > b.first_name) {
          return 1
        }

        if (a.last_name < b.last_name) {
          return -1
        }

        if (a.last_name > b.last_name) {
          return 1
        }

        return 0
      })

      this.users = users
    })
  }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
</style>

// src/components/App/App.jsx
import React from 'react'
import PropTypes from 'prop-types'
import firebase from 'firebase'

import TableRow from '../TableRow'

class App extends React.Component {
  constructor(props) {
    super(props)

    this.state = {
      users: []
    }
  }

  componentDidMount() {
    const config = {
      apiKey: "AIzaSyCN44MXJmFQW42p8VIn7UXn7PxCf2rnVFM",
      authDomain: "stack-overgol-bot.firebaseapp.com",
      databaseURL: "https://stack-overgol-bot.firebaseio.com",
      projectId: "stack-overgol-bot",
      storageBucket: "stack-overgol-bot.appspot.com",
      messagingSenderId: "564241331900"
    }

    if (!firebase.apps.length) {
      firebase.initializeApp(config)
    }

    const db = firebase.database()

    db.ref().child('/users').once('value').then(s => {
      const users = Object.values(s.val()).sort((a, b) => {
        if (a.first_name < b.first_name) {
          return -1
        }

        if (a.first_name > b.first_name) {
          return 1
        }

        if (a.last_name < b.last_name) {
          return -1
        }

        if (a.last_name > b.last_name) {
          return 1
        }

        return 0
      })
      this.setState({ users })
    })
  }

  render() {
    return (
      <div>
        <h1>Soccer Web</h1>

        <table>
          <thead>
            <tr>
              <th>First Name</th><th>Last Name</th><th>Rating</th><th>Subcriber</th><th>Admin</th>
            </tr>
          </thead>
          <tbody>
            {this.state.users && this.state.users.map(user => <TableRow key={user.uid} user={user} />)}
          </tbody>
        </table>
      </div>
    )
  }
}

export default App
